server:
  port: 8096


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # Use cj for modern drivers
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop, validate
    show-sql: true
  #flyway:
    #enabled: true
    #baseline-on-migrate: true
    #ignore-missing-migrations: true
    #out-of-order: true

  application:
    security:
      jwt:
        # Use a secure, HS256-compatible, Base64-encoded key string in production
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        # 15 minutes in milliseconds
        access-token-expiration: 900000
        # 7 days in milliseconds
        refresh-token-expiration: 604800000
# Mandatory property to trigger autoconfiguration

  mail:
     host: smtp.gmail.com
     port: 587
jwt:
  secret: mySuperSecretKeyForJwtAuthentication123456
  expiration: 3600000
  refresh-token-expiration: 604800000





