server:
  port: 8095


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_edutech_auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # Use cj for modern drivers
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop, validate
    show-sql: true
  application:
    name: api-gateway
    security:
      jwt:
        # Use a secure, HS256-compatible, Base64-encoded key string in production
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        # 15 minutes in milliseconds
        access-token-expiration: 900000
        # 7 days in milliseconds
        refresh-token-expiration: 604800000





